version: '3'

services:
  mongodb:
    image: mongo:bionic
    container_name: todo-back-mongodb
    ports:
      - '27017:27017'
    env_file:
      - .env
    volumes:
      - ./mongodb/data/db:/data/db
      - ./mongodb/data/logs:/data/logs
      - ./mongodb/mongod.conf:/etc/mongod.conf
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    command: mongod --config /etc/mongod.conf

  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - '8080:1080'
      - '8025:1025'
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
